# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFGenerate', '0003_auto_20170929_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.EmailField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('designation', models.TextField(max_length=1000)),
                ('company', models.TextField(max_length=1000)),
                ('contactno', models.TextField(max_length=1000)),
                ('email', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=1000)),
                ('interest1', models.TextField(max_length=1000)),
                ('interest2', models.TextField(max_length=1000)),
                ('interest3', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(max_length=1000)),
            ],
        ),
    ]
